# Generated by Django 2.1.5 on 2019-02-14 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(default='sandip', upload_to=''),
            preserve_default=False,
        ),
    ]
